// data/schoolData.ts

export interface Student {
  id: string
  fullName: string
  studentId: string
  className: string
  gender: "Male" | "Female"
  dateOfBirth: string
  age: number
  guardianName: string
  contactInfo: {
    phone: string
    email: string
    address: string
  }
  enrollmentStatus: "Active" | "Transferred" | "Graduated" | "Suspended"
  subjects: string[]
  academicRecord?: {
    subject: string
    test: number
    midTerm: number
    exam: number
    total: number
    grade: string
  }[]
  enrollmentDate: string
  medicalInfo?: {
    allergies: string[]
    emergencyContact: string
  }
}

export interface ClassGroup {
  level: string
  classes: string[]
  subjects: string[]
}

export const classGroups: ClassGroup[] = [
  {
    level: "Creche",
    classes: ["Creche 1", "Creche 2", "Creche 3"],
    subjects: ["Rhymes", "Drawing", "Number Work"],
  },
  {
    level: "Nursery",
    classes: ["Nursery 1", "Nursery 2", "Nursery 3"],
    subjects: ["Phonics", "Storytelling", "Basic Science"],
  },
  {
    level: "Primary",
    classes: ["Primary 1", "Primary 2", "Primary 3", "Primary 4", "Primary 5", "Primary 6"],
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
  },
  {
    level: "Secondary",
    classes: ["JSS 1", "JSS 2", "JSS 3", "SS 1", "SS 2", "SS 3"],
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
  },
]

export const sampleStudents: Student[] = [
  // Creche 1 Students (8 students)
  {
    id: "1",
    fullName: "Chioma Adebayo",
    studentId: "CRE001",
    className: "Creche 1",
    gender: "Female",
    dateOfBirth: "2021-04-15",
    age: 3,
    guardianName: "Mrs. Folake Adebayo",
    contactInfo: {
      phone: "+234 803 123 4567",
      email: "folake.adebayo@email.com",
      address: "12 Victoria Island, Lagos",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2023-09-01",
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 803 123 4568",
    },
  },
  {
    id: "2",
    fullName: "Emeka Okafor",
    studentId: "CRE002",
    className: "Creche 1",
    gender: "Male",
    dateOfBirth: "2021-06-22",
    age: 3,
    guardianName: "Mr. Peter Okafor",
    contactInfo: {
      phone: "+234 805 987 6543",
      email: "peter.okafor@email.com",
      address: "8 New Haven, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2023-09-01",
    medicalInfo: {
      allergies: ["Milk"],
      emergencyContact: "+234 805 987 6544",
    },
  },
  {
    id: "3",
    fullName: "Aisha Bello",
    studentId: "CRE003",
    className: "Creche 1",
    gender: "Female",
    dateOfBirth: "2021-08-10",
    age: 3,
    guardianName: "Alhaji Musa Bello",
    contactInfo: {
      phone: "+234 807 456 7890",
      email: "musa.bello@email.com",
      address: "45 Ahmadu Bello Way, Kaduna",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2023-09-01",
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 807 456 7891",
    },
  },
  {
    id: "4",
    fullName: "David Okoro",
    studentId: "CRE004",
    className: "Creche 1",
    gender: "Male",
    dateOfBirth: "2021-03-28",
    age: 3,
    guardianName: "Dr. Grace Okoro",
    contactInfo: {
      phone: "+234 809 234 5678",
      email: "grace.okoro@email.com",
      address: "15 Aba Road, Port Harcourt",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2023-09-01",
    medicalInfo: {
      allergies: ["Peanuts"],
      emergencyContact: "+234 809 234 5679",
    },
  },
  {
    id: "5",
    fullName: "Fatima Yusuf",
    studentId: "CRE005",
    className: "Creche 1",
    gender: "Female",
    dateOfBirth: "2021-07-14",
    age: 3,
    guardianName: "Mrs. Amina Yusuf",
    contactInfo: {
      phone: "+234 806 345 6789",
      email: "amina.yusuf@email.com",
      address: "22 Garki, Abuja",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2023-09-01",
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 806 345 6790",
    },
  },
  {
    id: "6",
    fullName: "Samuel Nwachukwu",
    studentId: "CRE006",
    className: "Creche 1",
    gender: "Male",
    dateOfBirth: "2021-05-03",
    age: 3,
    guardianName: "Mr. Chukwu Nwachukwu",
    contactInfo: {
      phone: "+234 808 567 8901",
      email: "chukwu.nwachukwu@email.com",
      address: "33 Independence Layout, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2023-09-01",
    medicalInfo: {
      allergies: ["Dust"],
      emergencyContact: "+234 808 567 8902",
    },
  },
  {
    id: "7",
    fullName: "Blessing Adamu",
    studentId: "CRE007",
    className: "Creche 1",
    gender: "Female",
    dateOfBirth: "2021-09-18",
    age: 3,
    guardianName: "Mrs. Mary Adamu",
    contactInfo: {
      phone: "+234 810 678 9012",
      email: "mary.adamu@email.com",
      address: "7 Maitama, Abuja",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2023-09-01",
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 810 678 9013",
    },
  },
  {
    id: "8",
    fullName: "Joseph Eze",
    studentId: "CRE008",
    className: "Creche 1",
    gender: "Male",
    dateOfBirth: "2021-02-25",
    age: 3,
    guardianName: "Mr. Emmanuel Eze",
    contactInfo: {
      phone: "+234 812 789 0123",
      email: "emmanuel.eze@email.com",
      address: "19 Coal City, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2023-09-01",
    medicalInfo: {
      allergies: ["Shellfish"],
      emergencyContact: "+234 812 789 0124",
    },
  },

  // Creche 2 Students (8 students)
  {
    id: "9",
    fullName: "Kemi Ogundimu",
    studentId: "CRE009",
    className: "Creche 2",
    gender: "Female",
    dateOfBirth: "2020-11-12",
    age: 4,
    guardianName: "Dr. Tunde Ogundimu",
    contactInfo: {
      phone: "+234 814 890 1234",
      email: "tunde.ogundimu@email.com",
      address: "25 Ikeja GRA, Lagos",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2022-09-01",
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 814 890 1235",
    },
  },
  {
    id: "10",
    fullName: "Ibrahim Sani",
    studentId: "CRE010",
    className: "Creche 2",
    gender: "Male",
    dateOfBirth: "2020-08-07",
    age: 4,
    guardianName: "Mallam Sani Ibrahim",
    contactInfo: {
      phone: "+234 816 901 2345",
      email: "sani.ibrahim@email.com",
      address: "11 Sabon Gari, Kano",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2022-09-01",
    medicalInfo: {
      allergies: ["Eggs"],
      emergencyContact: "+234 816 901 2346",
    },
  },
  {
    id: "11",
    fullName: "Grace Okonkwo",
    studentId: "CRE011",
    className: "Creche 2",
    gender: "Female",
    dateOfBirth: "2020-12-30",
    age: 4,
    guardianName: "Mrs. Ngozi Okonkwo",
    contactInfo: {
      phone: "+234 818 012 3456",
      email: "ngozi.okonkwo@email.com",
      address: "5 Awka Road, Onitsha",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2022-09-01",
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 818 012 3457",
    },
  },
  {
    id: "12",
    fullName: "Michael Adeyemi",
    studentId: "CRE012",
    className: "Creche 2",
    gender: "Male",
    dateOfBirth: "2020-10-15",
    age: 4,
    guardianName: "Prof. Adeyemi Michael",
    contactInfo: {
      phone: "+234 820 123 4567",
      email: "adeyemi.michael@email.com",
      address: "18 Bodija, Ibadan",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2022-09-01",
    medicalInfo: {
      allergies: ["Nuts"],
      emergencyContact: "+234 820 123 4568",
    },
  },
  {
    id: "13",
    fullName: "Hauwa Garba",
    studentId: "CRE013",
    className: "Creche 2",
    gender: "Female",
    dateOfBirth: "2020-09-22",
    age: 4,
    guardianName: "Dr. Garba Hauwa",
    contactInfo: {
      phone: "+234 822 234 5678",
      email: "garba.hauwa@email.com",
      address: "9 Ungwan Rimi, Kaduna",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2022-09-01",
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 822 234 5679",
    },
  },
  {
    id: "14",
    fullName: "Daniel Okpara",
    studentId: "CRE014",
    className: "Creche 2",
    gender: "Male",
    dateOfBirth: "2020-07-08",
    age: 4,
    guardianName: "Mr. Okpara Daniel",
    contactInfo: {
      phone: "+234 824 345 6789",
      email: "okpara.daniel@email.com",
      address: "14 Owerri Road, Aba",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2022-09-01",
    medicalInfo: {
      allergies: ["Soy"],
      emergencyContact: "+234 824 345 6790",
    },
  },
  {
    id: "15",
    fullName: "Zainab Usman",
    studentId: "CRE015",
    className: "Creche 2",
    gender: "Female",
    dateOfBirth: "2020-06-19",
    age: 4,
    guardianName: "Alhaji Usman Zainab",
    contactInfo: {
      phone: "+234 826 456 7890",
      email: "usman.zainab@email.com",
      address: "21 Wuse II, Abuja",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2022-09-01",
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 826 456 7891",
    },
  },
  {
    id: "16",
    fullName: "Victor Nnaji",
    studentId: "CRE016",
    className: "Creche 2",
    gender: "Male",
    dateOfBirth: "2020-05-11",
    age: 4,
    guardianName: "Mrs. Nnaji Victor",
    contactInfo: {
      phone: "+234 828 567 8901",
      email: "nnaji.victor@email.com",
      address: "6 Trans Ekulu, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2022-09-01",
    medicalInfo: {
      allergies: ["Fish"],
      emergencyContact: "+234 828 567 8902",
    },
  },

  // Creche 3 Students (8 students)
  {
    id: "17",
    fullName: "Adunni Bakare",
    studentId: "CRE017",
    className: "Creche 3",
    gender: "Female",
    dateOfBirth: "2019-12-05",
    age: 5,
    guardianName: "Mr. Bakare Adunni",
    contactInfo: {
      phone: "+234 830 678 9012",
      email: "bakare.adunni@email.com",
      address: "13 Surulere, Lagos",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2021-09-01",
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 830 678 9013",
    },
  },
  {
    id: "18",
    fullName: "Chinedu Obi",
    studentId: "CRE018",
    className: "Creche 3",
    gender: "Male",
    dateOfBirth: "2019-10-28",
    age: 5,
    guardianName: "Dr. Obi Chinedu",
    contactInfo: {
      phone: "+234 832 789 0123",
      email: "obi.chinedu@email.com",
      address: "27 Asaba Road, Onitsha",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2021-09-01",
    medicalInfo: {
      allergies: ["Wheat"],
      emergencyContact: "+234 832 789 0124",
    },
  },
  {
    id: "19",
    fullName: "Maryam Aliyu",
    studentId: "CRE019",
    className: "Creche 3",
    gender: "Female",
    dateOfBirth: "2019-11-16",
    age: 5,
    guardianName: "Mrs. Aliyu Maryam",
    contactInfo: {
      phone: "+234 834 890 1234",
      email: "aliyu.maryam@email.com",
      address: "4 Barnawa, Kaduna",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2021-09-01",
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 834 890 1235",
    },
  },
  {
    id: "20",
    fullName: "Tochukwu Eze",
    studentId: "CRE020",
    className: "Creche 3",
    gender: "Male",
    dateOfBirth: "2019-09-03",
    age: 5,
    guardianName: "Mr. Eze Tochukwu",
    contactInfo: {
      phone: "+234 836 901 2345",
      email: "eze.tochukwu@email.com",
      address: "16 Nike Lake, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2021-09-01",
    medicalInfo: {
      allergies: ["Dairy"],
      emergencyContact: "+234 836 901 2346",
    },
  },
  {
    id: "21",
    fullName: "Funmi Adebola",
    studentId: "CRE021",
    className: "Creche 3",
    gender: "Female",
    dateOfBirth: "2019-08-21",
    age: 5,
    guardianName: "Mrs. Adebola Funmi",
    contactInfo: {
      phone: "+234 838 012 3456",
      email: "adebola.funmi@email.com",
      address: "10 Abeokuta Road, Lagos",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2021-09-01",
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 838 012 3457",
    },
  },
  {
    id: "22",
    fullName: "Abdullahi Musa",
    studentId: "CRE022",
    className: "Creche 3",
    gender: "Male",
    dateOfBirth: "2019-07-14",
    age: 5,
    guardianName: "Mallam Musa Abdullahi",
    contactInfo: {
      phone: "+234 840 123 4567",
      email: "musa.abdullahi@email.com",
      address: "23 Fagge, Kano",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2021-09-01",
    medicalInfo: {
      allergies: ["Citrus"],
      emergencyContact: "+234 840 123 4568",
    },
  },
  {
    id: "23",
    fullName: "Chioma Ugwu",
    studentId: "CRE023",
    className: "Creche 3",
    gender: "Female",
    dateOfBirth: "2019-06-07",
    age: 5,
    guardianName: "Dr. Ugwu Chioma",
    contactInfo: {
      phone: "+234 842 234 5678",
      email: "ugwu.chioma@email.com",
      address: "8 University Road, Nsukka",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2021-09-01",
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 842 234 5679",
    },
  },
  {
    id: "24",
    fullName: "Olumide Ajayi",
    studentId: "CRE024",
    className: "Creche 3",
    gender: "Male",
    dateOfBirth: "2019-05-25",
    age: 5,
    guardianName: "Mr. Ajayi Olumide",
    contactInfo: {
      phone: "+234 844 345 6789",
      email: "ajayi.olumide@email.com",
      address: "17 Oke Ado, Ibadan",
    },
    enrollmentStatus: "Active",
    subjects: ["Rhymes", "Drawing", "Number Work"],
    enrollmentDate: "2021-09-01",
    medicalInfo: {
      allergies: ["Strawberries"],
      emergencyContact: "+234 844 345 6790",
    },
  },

  // Nursery 1 Students (8 students)
  {
    id: "25",
    fullName: "Esther Okwu",
    studentId: "NUR001",
    className: "Nursery 1",
    gender: "Female",
    dateOfBirth: "2018-11-20",
    age: 6,
    guardianName: "Mrs. Okwu Esther",
    contactInfo: {
      phone: "+234 846 456 7890",
      email: "okwu.esther@email.com",
      address: "20 Ogui Road, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2020-09-01",
    academicRecord: [
      { subject: "Phonics", test: 8, midTerm: 16, exam: 58, total: 82, grade: "A" },
      { subject: "Storytelling", test: 9, midTerm: 17, exam: 62, total: 88, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 846 456 7891",
    },
  },
  {
    id: "26",
    fullName: "Kunle Adeyinka",
    studentId: "NUR002",
    className: "Nursery 1",
    gender: "Male",
    dateOfBirth: "2018-09-14",
    age: 6,
    guardianName: "Mr. Adeyinka Kunle",
    contactInfo: {
      phone: "+234 848 567 8901",
      email: "adeyinka.kunle@email.com",
      address: "31 Ring Road, Ibadan",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2020-09-01",
    academicRecord: [
      { subject: "Phonics", test: 7, midTerm: 15, exam: 55, total: 77, grade: "B" },
      { subject: "Basic Science", test: 8, midTerm: 16, exam: 60, total: 84, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Pollen"],
      emergencyContact: "+234 848 567 8902",
    },
  },
  {
    id: "27",
    fullName: "Amina Hassan",
    studentId: "NUR003",
    className: "Nursery 1",
    gender: "Female",
    dateOfBirth: "2018-12-08",
    age: 6,
    guardianName: "Dr. Hassan Amina",
    contactInfo: {
      phone: "+234 850 678 9012",
      email: "hassan.amina@email.com",
      address: "15 Tudun Wada, Kaduna",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2020-09-01",
    academicRecord: [
      { subject: "Phonics", test: 9, midTerm: 18, exam: 65, total: 92, grade: "A" },
      { subject: "Storytelling", test: 8, midTerm: 17, exam: 63, total: 88, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 850 678 9013",
    },
  },
  {
    id: "28",
    fullName: "Chukwuemeka Okafor",
    studentId: "NUR004",
    className: "Nursery 1",
    gender: "Male",
    dateOfBirth: "2018-10-22",
    age: 6,
    guardianName: "Mr. Okafor Chukwuemeka",
    contactInfo: {
      phone: "+234 852 789 0123",
      email: "okafor.chukwuemeka@email.com",
      address: "9 Achara Layout, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2020-09-01",
    academicRecord: [
      { subject: "Basic Science", test: 7, midTerm: 14, exam: 52, total: 73, grade: "B" },
      { subject: "Phonics", test: 8, midTerm: 16, exam: 58, total: 82, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Latex"],
      emergencyContact: "+234 852 789 0124",
    },
  },
  {
    id: "29",
    fullName: "Folake Oni",
    studentId: "NUR005",
    className: "Nursery 1",
    gender: "Female",
    dateOfBirth: "2018-08-16",
    age: 6,
    guardianName: "Mrs. Oni Folake",
    contactInfo: {
      phone: "+234 854 890 1234",
      email: "oni.folake@email.com",
      address: "26 Yaba, Lagos",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2020-09-01",
    academicRecord: [
      { subject: "Storytelling", test: 9, midTerm: 18, exam: 67, total: 94, grade: "A" },
      { subject: "Phonics", test: 8, midTerm: 17, exam: 61, total: 86, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 854 890 1235",
    },
  },
  {
    id: "30",
    fullName: "Yusuf Garba",
    studentId: "NUR006",
    className: "Nursery 1",
    gender: "Male",
    dateOfBirth: "2018-07-30",
    age: 6,
    guardianName: "Mallam Garba Yusuf",
    contactInfo: {
      phone: "+234 856 901 2345",
      email: "garba.yusuf@email.com",
      address: "12 Nasarawa GRA, Kano",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2020-09-01",
    academicRecord: [
      { subject: "Basic Science", test: 8, midTerm: 15, exam: 56, total: 79, grade: "B" },
      { subject: "Phonics", test: 7, midTerm: 16, exam: 59, total: 82, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Dust mites"],
      emergencyContact: "+234 856 901 2346",
    },
  },
  {
    id: "31",
    fullName: "Ngozi Ibe",
    studentId: "NUR007",
    className: "Nursery 1",
    gender: "Female",
    dateOfBirth: "2018-06-12",
    age: 6,
    guardianName: "Dr. Ibe Ngozi",
    contactInfo: {
      phone: "+234 858 012 3456",
      email: "ibe.ngozi@email.com",
      address: "18 Owerri Road, Aba",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2020-09-01",
    academicRecord: [
      { subject: "Phonics", test: 9, midTerm: 17, exam: 64, total: 90, grade: "A" },
      {
        subject: "Storytelling",
        test: 8,
        midTerm: 16,
        exam: 60,
        total: 84,
        grade: "A",
      },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 858 012 3457",
    },
  },
  {
    id: "32",
    fullName: "Segun Adebayo",
    studentId: "NUR008",
    className: "Nursery 1",
    gender: "Male",
    dateOfBirth: "2018-05-25",
    age: 6,
    guardianName: "Mr. Adebayo Segun",
    contactInfo: {
      phone: "+234 860 123 4567",
      email: "adebayo.segun@email.com",
      address: "24 Agege, Lagos",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2020-09-01",
    academicRecord: [
      { subject: "Basic Science", test: 7, midTerm: 15, exam: 54, total: 76, grade: "B" },
      { subject: "Phonics", test: 8, midTerm: 16, exam: 57, total: 81, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Cats"],
      emergencyContact: "+234 860 123 4568",
    },
  },

  // Nursery 2 Students (8 students)
  {
    id: "33",
    fullName: "Ada Nwachukwu",
    studentId: "NUR009",
    className: "Nursery 2",
    gender: "Female",
    dateOfBirth: "2017-11-15",
    age: 7,
    guardianName: "Mrs. Grace Nwachukwu",
    contactInfo: {
      phone: "+234 862 234 5678",
      email: "grace.nwachukwu@email.com",
      address: "22 Independence Layout, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2019-09-01",
    academicRecord: [
      { subject: "Phonics", test: 9, midTerm: 18, exam: 62, total: 89, grade: "A" },
      { subject: "Storytelling", test: 8, midTerm: 17, exam: 58, total: 83, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 862 234 5679",
    },
  },
  {
    id: "34",
    fullName: "Kelechi Okoro",
    studentId: "NUR010",
    className: "Nursery 2",
    gender: "Male",
    dateOfBirth: "2017-09-28",
    age: 7,
    guardianName: "Mr. Chukwu Okoro",
    contactInfo: {
      phone: "+234 864 345 6789",
      email: "chukwu.okoro@email.com",
      address: "15 Aba Road, Port Harcourt",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2019-09-01",
    academicRecord: [
      { subject: "Basic Science", test: 8, midTerm: 16, exam: 59, total: 83, grade: "A" },
      { subject: "Phonics", test: 7, midTerm: 15, exam: 56, total: 78, grade: "B" },
    ],
    medicalInfo: {
      allergies: ["Peanuts"],
      emergencyContact: "+234 864 345 6790",
    },
  },
  {
    id: "35",
    fullName: "Halima Abdullahi",
    studentId: "NUR011",
    className: "Nursery 2",
    gender: "Female",
    dateOfBirth: "2017-12-03",
    age: 7,
    guardianName: "Dr. Amina Abdullahi",
    contactInfo: {
      phone: "+234 866 456 7890",
      email: "amina.abdullahi@email.com",
      address: "12 Gimbiya Street, Abuja",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2019-09-01",
    academicRecord: [
      { subject: "Phonics", test: 9, midTerm: 17, exam: 63, total: 89, grade: "A" },
      { subject: "Storytelling", test: 8, midTerm: 18, exam: 65, total: 91, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 866 456 7891",
    },
  },
  {
    id: "36",
    fullName: "Obinna Eze",
    studentId: "NUR012",
    className: "Nursery 2",
    gender: "Male",
    dateOfBirth: "2017-10-17",
    age: 7,
    guardianName: "Mr. Emmanuel Eze",
    contactInfo: {
      phone: "+234 868 567 8901",
      email: "emmanuel.eze@email.com",
      address: "19 Coal City, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2019-09-01",
    academicRecord: [
      { subject: "Basic Science", test: 7, midTerm: 16, exam: 57, total: 80, grade: "A" },
      { subject: "Phonics", test: 8, midTerm: 15, exam: 58, total: 81, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Shellfish"],
      emergencyContact: "+234 868 567 8902",
    },
  },
  {
    id: "37",
    fullName: "Temilola Adebayo",
    studentId: "NUR013",
    className: "Nursery 2",
    gender: "Female",
    dateOfBirth: "2017-08-09",
    age: 7,
    guardianName: "Mrs. Folake Adebayo",
    contactInfo: {
      phone: "+234 870 678 9012",
      email: "folake.adebayo@email.com",
      address: "12 Victoria Island, Lagos",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2019-09-01",
    academicRecord: [
      { subject: "Storytelling", test: 9, midTerm: 18, exam: 66, total: 93, grade: "A" },
      { subject: "Phonics", test: 8, midTerm: 17, exam: 61, total: 86, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 870 678 9013",
    },
  },
  {
    id: "38",
    fullName: "Bashir Usman",
    studentId: "NUR014",
    className: "Nursery 2",
    gender: "Male",
    dateOfBirth: "2017-07-21",
    age: 7,
    guardianName: "Alhaji Usman Bashir",
    contactInfo: {
      phone: "+234 872 789 0123",
      email: "usman.bashir@email.com",
      address: "21 Wuse II, Abuja",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2019-09-01",
    academicRecord: [
      { subject: "Basic Science", test: 8, midTerm: 16, exam: 60, total: 84, grade: "A" },
      { subject: "Phonics", test: 7, midTerm: 15, exam: 55, total: 77, grade: "B" },
    ],
    medicalInfo: {
      allergies: ["Dust"],
      emergencyContact: "+234 872 789 0124",
    },
  },
  {
    id: "39",
    fullName: "Chinelo Okafor",
    studentId: "NUR015",
    className: "Nursery 2",
    gender: "Female",
    dateOfBirth: "2017-06-14",
    age: 7,
    guardianName: "Mr. Peter Okafor",
    contactInfo: {
      phone: "+234 874 890 1234",
      email: "peter.okafor@email.com",
      address: "8 New Haven, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2019-09-01",
    academicRecord: [
      { subject: "Phonics", test: 8, midTerm: 17, exam: 62, total: 87, grade: "A" },
      { subject: "Storytelling", test: 9, midTerm: 16, exam: 59, total: 84, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Milk"],
      emergencyContact: "+234 874 890 1235",
    },
  },
  {
    id: "40",
    fullName: "Taiwo Adeyemi",
    studentId: "NUR016",
    className: "Nursery 2",
    gender: "Male",
    dateOfBirth: "2017-05-07",
    age: 7,
    guardianName: "Prof. Adeyemi Taiwo",
    contactInfo: {
      phone: "+234 876 901 2345",
      email: "adeyemi.taiwo@email.com",
      address: "18 Bodija, Ibadan",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2019-09-01",
    academicRecord: [
      { subject: "Basic Science", test: 7, midTerm: 15, exam: 53, total: 75, grade: "B" },
      { subject: "Phonics", test: 8, midTerm: 16, exam: 58, total: 82, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Nuts"],
      emergencyContact: "+234 876 901 2346",
    },
  },

  // Nursery 3 Students (8 students)
  {
    id: "41",
    fullName: "Ifeoma Okwu",
    studentId: "NUR017",
    className: "Nursery 3",
    gender: "Female",
    dateOfBirth: "2016-11-22",
    age: 8,
    guardianName: "Mrs. Okwu Ifeoma",
    contactInfo: {
      phone: "+234 878 012 3456",
      email: "okwu.ifeoma@email.com",
      address: "20 Ogui Road, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2018-09-01",
    academicRecord: [
      { subject: "Phonics", test: 9, midTerm: 18, exam: 68, total: 95, grade: "A" },
      { subject: "Storytelling", test: 8, midTerm: 17, exam: 65, total: 90, grade: "A" },
      { subject: "Basic Science", test: 8, midTerm: 16, exam: 62, total: 86, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 878 012 3457",
    },
  },
  {
    id: "42",
    fullName: "Adamu Garba",
    studentId: "NUR018",
    className: "Nursery 3",
    gender: "Male",
    dateOfBirth: "2016-09-15",
    age: 8,
    guardianName: "Dr. Garba Adamu",
    contactInfo: {
      phone: "+234 880 123 4567",
      email: "garba.adamu@email.com",
      address: "9 Ungwan Rimi, Kaduna",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2018-09-01",
    academicRecord: [
      { subject: "Basic Science", test: 8, midTerm: 17, exam: 64, total: 89, grade: "A" },
      { subject: "Phonics", test: 7, midTerm: 16, exam: 59, total: 82, grade: "A" },
      { subject: "Storytelling", test: 9, midTerm: 18, exam: 66, total: 93, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Pollen"],
      emergencyContact: "+234 880 123 4568",
    },
  },
  {
    id: "43",
    fullName: "Chiamaka Nnaji",
    studentId: "NUR019",
    className: "Nursery 3",
    gender: "Female",
    dateOfBirth: "2016-12-08",
    age: 8,
    guardianName: "Mrs. Nnaji Chiamaka",
    contactInfo: {
      phone: "+234 882 234 5678",
      email: "nnaji.chiamaka@email.com",
      address: "6 Trans Ekulu, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2018-09-01",
    academicRecord: [
      { subject: "Phonics", test: 9, midTerm: 17, exam: 67, total: 93, grade: "A" },
      { subject: "Storytelling", test: 8, midTerm: 18, exam: 63, total: 89, grade: "A" },
      { subject: "Basic Science", test: 7, midTerm: 16, exam: 61, total: 84, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Fish"],
      emergencyContact: "+234 882 234 5679",
    },
  },
  {
    id: "44",
    fullName: "Oluwaseun Bakare",
    studentId: "NUR020",
    className: "Nursery 3",
    gender: "Male",
    dateOfBirth: "2016-10-30",
    age: 8,
    guardianName: "Mr. Bakare Oluwaseun",
    contactInfo: {
      phone: "+234 884 345 6789",
      email: "bakare.oluwaseun@email.com",
      address: "13 Surulere, Lagos",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2018-09-01",
    academicRecord: [
      { subject: "Basic Science", test: 8, midTerm: 16, exam: 60, total: 84, grade: "A" },
      { subject: "Phonics", test: 7, midTerm: 15, exam: 57, total: 79, grade: "B" },
      { subject: "Storytelling", test: 9, midTerm: 17, exam: 64, total: 90, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 884 345 6790",
    },
  },
  {
    id: "45",
    fullName: "Safiya Aliyu",
    studentId: "NUR021",
    className: "Nursery 3",
    gender: "Female",
    dateOfBirth: "2016-08-18",
    age: 8,
    guardianName: "Mrs. Aliyu Safiya",
    contactInfo: {
      phone: "+234 886 456 7890",
      email: "aliyu.safiya@email.com",
      address: "4 Barnawa, Kaduna",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2018-09-01",
    academicRecord: [
      { subject: "Phonics", test: 8, midTerm: 17, exam: 65, total: 90, grade: "A" },
      { subject: "Storytelling", test: 9, midTerm: 18, exam: 67, total: 94, grade: "A" },
      { subject: "Basic Science", test: 8, midTerm: 16, exam: 62, total: 86, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 886 456 7891",
    },
  },
  {
    id: "46",
    fullName: "Chukwudi Obi",
    studentId: "NUR022",
    className: "Nursery 3",
    gender: "Male",
    dateOfBirth: "2016-07-11",
    age: 8,
    guardianName: "Dr. Obi Chukwudi",
    contactInfo: {
      phone: "+234 888 567 8901",
      email: "obi.chukwudi@email.com",
      address: "27 Asaba Road, Onitsha",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2018-09-01",
    academicRecord: [
      { subject: "Basic Science", test: 7, midTerm: 16, exam: 58, total: 81, grade: "A" },
      { subject: "Phonics", test: 8, midTerm: 17, exam: 63, total: 88, grade: "A" },
      { subject: "Storytelling", test: 9, midTerm: 18, exam: 65, total: 92, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Wheat"],
      emergencyContact: "+234 888 567 8902",
    },
  },
  {
    id: "47",
    fullName: "Bukola Adebola",
    studentId: "NUR023",
    className: "Nursery 3",
    gender: "Female",
    dateOfBirth: "2016-06-25",
    age: 8,
    guardianName: "Mrs. Adebola Bukola",
    contactInfo: {
      phone: "+234 890 678 9012",
      email: "adebola.bukola@email.com",
      address: "10 Abeokuta Road, Lagos",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2018-09-01",
    academicRecord: [
      { subject: "Phonics", test: 9, midTerm: 18, exam: 69, total: 96, grade: "A" },
      { subject: "Storytelling", test: 8, midTerm: 17, exam: 66, total: 91, grade: "A" },
      { subject: "Basic Science", test: 8, midTerm: 16, exam: 63, total: 87, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 890 678 9013",
    },
  },
  {
    id: "48",
    fullName: "Suleiman Musa",
    studentId: "NUR024",
    className: "Nursery 3",
    gender: "Male",
    dateOfBirth: "2016-05-13",
    age: 8,
    guardianName: "Mallam Musa Suleiman",
    contactInfo: {
      phone: "+234 892 789 0123",
      email: "musa.suleiman@email.com",
      address: "23 Fagge, Kano",
    },
    enrollmentStatus: "Active",
    subjects: ["Phonics", "Storytelling", "Basic Science"],
    enrollmentDate: "2018-09-01",
    academicRecord: [
      { subject: "Basic Science", test: 7, midTerm: 15, exam: 56, total: 78, grade: "B" },
      { subject: "Phonics", test: 8, midTerm: 16, exam: 60, total: 84, grade: "A" },
      { subject: "Storytelling", test: 9, midTerm: 17, exam: 64, total: 90, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Citrus"],
      emergencyContact: "+234 892 789 0124",
    },
  },

  // Primary 1 Students (8 students)
  {
    id: "49",
    fullName: "Chidinma Ugwu",
    studentId: "PRI001",
    className: "Primary 1",
    gender: "Female",
    dateOfBirth: "2015-11-28",
    age: 9,
    guardianName: "Dr. Ugwu Chidinma",
    contactInfo: {
      phone: "+234 894 890 1234",
      email: "ugwu.chidinma@email.com",
      address: "8 University Road, Nsukka",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2017-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 8, midTerm: 17, exam: 65, total: 90, grade: "A" },
      { subject: "English", test: 9, midTerm: 18, exam: 67, total: 94, grade: "A" },
      { subject: "Basic Science", test: 8, midTerm: 16, exam: 62, total: 86, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 894 890 1235",
    },
  },
  {
    id: "50",
    fullName: "Tunde Ajayi",
    studentId: "PRI002",
    className: "Primary 1",
    gender: "Male",
    dateOfBirth: "2015-09-14",
    age: 9,
    guardianName: "Mr. Ajayi Tunde",
    contactInfo: {
      phone: "+234 896 901 2345",
      email: "ajayi.tunde@email.com",
      address: "17 Oke Ado, Ibadan",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2017-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 7, midTerm: 16, exam: 58, total: 81, grade: "A" },
      { subject: "English", test: 8, midTerm: 17, exam: 63, total: 88, grade: "A" },
      { subject: "Basic Science", test: 7, midTerm: 15, exam: 56, total: 78, grade: "B" },
    ],
    medicalInfo: {
      allergies: ["Strawberries"],
      emergencyContact: "+234 896 901 2346",
    },
  },
  {
    id: "51",
    fullName: "Rahmat Yusuf",
    studentId: "PRI003",
    className: "Primary 1",
    gender: "Female",
    dateOfBirth: "2015-12-06",
    age: 9,
    guardianName: "Mrs. Amina Yusuf",
    contactInfo: {
      phone: "+234 898 012 3456",
      email: "amina.yusuf@email.com",
      address: "22 Garki, Abuja",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2017-09-01",
    academicRecord: [
      { subject: "English", test: 9, midTerm: 18, exam: 68, total: 95, grade: "A" },
      { subject: "Mathematics", test: 8, midTerm: 17, exam: 64, total: 89, grade: "A" },
      { subject: "Civic Education", test: 8, midTerm: 16, exam: 61, total: 85, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 898 012 3457",
    },
  },
  {
    id: "52",
    fullName: "Ibrahim Bello",
    studentId: "PRI004",
    className: "Primary 1",
    gender: "Male",
    dateOfBirth: "2015-10-19",
    age: 9,
    guardianName: "Alhaji Musa Bello",
    contactInfo: {
      phone: "+234 900 123 4567",
      email: "musa.bello@email.com",
      address: "45 Ahmadu Bello Way, Kaduna",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2017-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 7, midTerm: 14, exam: 49, total: 70, grade: "B" },
      { subject: "English", test: 8, midTerm: 15, exam: 52, total: 75, grade: "B" },
      { subject: "Basic Science", test: 7, midTerm: 16, exam: 55, total: 78, grade: "B" },
    ],
    medicalInfo: {
      allergies: ["Dust"],
      emergencyContact: "+234 900 123 4568",
    },
  },
  {
    id: "53",
    fullName: "Adaeze Okonkwo",
    studentId: "PRI005",
    className: "Primary 1",
    gender: "Female",
    dateOfBirth: "2015-08-11",
    age: 9,
    guardianName: "Mrs. Ngozi Okonkwo",
    contactInfo: {
      phone: "+234 902 234 5678",
      email: "ngozi.okonkwo@email.com",
      address: "5 Awka Road, Onitsha",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2017-09-01",
    academicRecord: [
      { subject: "English", test: 9, midTerm: 17, exam: 66, total: 92, grade: "A" },
      { subject: "Mathematics", test: 8, midTerm: 16, exam: 62, total: 86, grade: "A" },
      { subject: "Basic Science", test: 8, midTerm: 17, exam: 63, total: 88, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 902 234 5679",
    },
  },
  {
    id: "54",
    fullName: "Kayode Adeyemi",
    studentId: "PRI006",
    className: "Primary 1",
    gender: "Male",
    dateOfBirth: "2015-07-23",
    age: 9,
    guardianName: "Prof. Adeyemi Kayode",
    contactInfo: {
      phone: "+234 904 345 6789",
      email: "adeyemi.kayode@email.com",
      address: "18 Bodija, Ibadan",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2017-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 8, midTerm: 17, exam: 64, total: 89, grade: "A" },
      { subject: "English", test: 7, midTerm: 16, exam: 59, total: 82, grade: "A" },
      { subject: "Basic Science", test: 8, midTerm: 15, exam: 57, total: 80, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Nuts"],
      emergencyContact: "+234 904 345 6790",
    },
  },
  {
    id: "55",
    fullName: "Asmau Garba",
    studentId: "PRI007",
    className: "Primary 1",
    gender: "Female",
    dateOfBirth: "2015-06-16",
    age: 9,
    guardianName: "Dr. Garba Asmau",
    contactInfo: {
      phone: "+234 906 456 7890",
      email: "garba.asmau@email.com",
      address: "9 Ungwan Rimi, Kaduna",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2017-09-01",
    academicRecord: [
      { subject: "English", test: 9, midTerm: 18, exam: 69, total: 96, grade: "A" },
      { subject: "Mathematics", test: 8, midTerm: 17, exam: 65, total: 90, grade: "A" },
      { subject: "Civic Education", test: 8, midTerm: 16, exam: 62, total: 86, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 906 456 7891",
    },
  },
  {
    id: "56",
    fullName: "Chukwuma Okpara",
    studentId: "PRI008",
    className: "Primary 1",
    gender: "Male",
    dateOfBirth: "2015-05-09",
    age: 9,
    guardianName: "Mr. Okpara Chukwuma",
    contactInfo: {
      phone: "+234 908 567 8901",
      email: "okpara.chukwuma@email.com",
      address: "14 Owerri Road, Aba",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2017-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 7, midTerm: 15, exam: 54, total: 76, grade: "B" },
      { subject: "English", test: 8, midTerm: 16, exam: 58, total: 82, grade: "A" },
      { subject: "Basic Science", test: 7, midTerm: 16, exam: 56, total: 79, grade: "B" },
    ],
    medicalInfo: {
      allergies: ["Soy"],
      emergencyContact: "+234 908 567 8902",
    },
  },

  // Primary 2 Students (8 students)
  {
    id: "57",
    fullName: "Amara Eze",
    studentId: "PRI009",
    className: "Primary 2",
    gender: "Female",
    dateOfBirth: "2014-11-21",
    age: 10,
    guardianName: "Mr. Eze Amara",
    contactInfo: {
      phone: "+234 910 678 9012",
      email: "eze.amara@email.com",
      address: "16 Nike Lake, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2016-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 8, midTerm: 17, exam: 66, total: 91, grade: "A" },
      { subject: "English", test: 9, midTerm: 18, exam: 68, total: 95, grade: "A" },
      { subject: "Basic Science", test: 8, midTerm: 16, exam: 63, total: 87, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Dairy"],
      emergencyContact: "+234 910 678 9013",
    },
  },
  {
    id: "58",
    fullName: "Bolaji Oni",
    studentId: "PRI010",
    className: "Primary 2",
    gender: "Male",
    dateOfBirth: "2014-09-13",
    age: 10,
    guardianName: "Mrs. Oni Bolaji",
    contactInfo: {
      phone: "+234 912 789 0123",
      email: "oni.bolaji@email.com",
      address: "26 Yaba, Lagos",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2016-09-01",
    academicRecord: [
      { subject: "English", test: 8, midTerm: 17, exam: 64, total: 89, grade: "A" },
      { subject: "Mathematics", test: 7, midTerm: 16, exam: 60, total: 83, grade: "A" },
      { subject: "Basic Science", test: 8, midTerm: 15, exam: 58, total: 81, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 912 789 0124",
    },
  },
  {
    id: "59",
    fullName: "Khadija Sani",
    studentId: "PRI011",
    className: "Primary 2",
    gender: "Female",
    dateOfBirth: "2014-12-05",
    age: 10,
    guardianName: "Mallam Sani Khadija",
    contactInfo: {
      phone: "+234 914 890 1234",
      email: "sani.khadija@email.com",
      address: "12 Nasarawa GRA, Kano",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2016-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 9, midTerm: 18, exam: 67, total: 94, grade: "A" },
      { subject: "English", test: 8, midTerm: 17, exam: 65, total: 90, grade: "A" },
      { subject: "Civic Education", test: 8, midTerm: 16, exam: 62, total: 86, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Dust mites"],
      emergencyContact: "+234 914 890 1235",
    },
  },
  {
    id: "60",
    fullName: "Emeka Okoro",
    studentId: "PRI012",
    className: "Primary 2",
    gender: "Male",
    dateOfBirth: "2014-10-17",
    age: 10,
    guardianName: "Mr. Chukwu Okoro",
    contactInfo: {
      phone: "+234 916 901 2345",
      email: "chukwu.okoro@email.com",
      address: "15 Aba Road, Port Harcourt",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2016-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 8, midTerm: 15, exam: 55, total: 78, grade: "B" },
      { subject: "English", test: 9, midTerm: 16, exam: 60, total: 85, grade: "A" },
      { subject: "Basic Science", test: 7, midTerm: 16, exam: 57, total: 80, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Peanuts"],
      emergencyContact: "+234 916 901 2346",
    },
  },
  {
    id: "61",
    fullName: "Nneka Ibe",
    studentId: "PRI013",
    className: "Primary 2",
    gender: "Female",
    dateOfBirth: "2014-08-29",
    age: 10,
    guardianName: "Dr. Ibe Nneka",
    contactInfo: {
      phone: "+234 918 012 3456",
      email: "ibe.nneka@email.com",
      address: "18 Owerri Road, Aba",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2016-09-01",
    academicRecord: [
      { subject: "English", test: 9, midTerm: 18, exam: 69, total: 96, grade: "A" },
      { subject: "Mathematics", test: 8, midTerm: 17, exam: 66, total: 91, grade: "A" },
      { subject: "Basic Science", test: 8, midTerm: 16, exam: 63, total: 87, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 918 012 3457",
    },
  },
  {
    id: "62",
    fullName: "Damilola Adebayo",
    studentId: "PRI014",
    className: "Primary 2",
    gender: "Male",
    dateOfBirth: "2014-07-12",
    age: 10,
    guardianName: "Mr. Adebayo Damilola",
    contactInfo: {
      phone: "+234 920 123 4567",
      email: "adebayo.damilola@email.com",
      address: "24 Agege, Lagos",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2016-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 7, midTerm: 16, exam: 59, total: 82, grade: "A" },
      { subject: "English", test: 8, midTerm: 17, exam: 62, total: 87, grade: "A" },
      { subject: "Basic Science", test: 7, midTerm: 15, exam: 56, total: 78, grade: "B" },
    ],
    medicalInfo: {
      allergies: ["Cats"],
      emergencyContact: "+234 920 123 4568",
    },
  },
  {
    id: "63",
    fullName: "Fatima Abdullahi",
    studentId: "PRI015",
    className: "Primary 2",
    gender: "Female",
    dateOfBirth: "2014-06-24",
    age: 10,
    guardianName: "Dr. Amina Abdullahi",
    contactInfo: {
      phone: "+234 922 234 5678",
      email: "amina.abdullahi@email.com",
      address: "12 Gimbiya Street, Abuja",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2016-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 9, midTerm: 18, exam: 68, total: 95, grade: "A" },
      { subject: "English", test: 8, midTerm: 17, exam: 65, total: 90, grade: "A" },
      { subject: "Civic Education", test: 8, midTerm: 16, exam: 62, total: 86, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 922 234 5679",
    },
  },
  {
    id: "64",
    fullName: "Chinedu Nwachukwu",
    studentId: "PRI016",
    className: "Primary 2",
    gender: "Male",
    dateOfBirth: "2014-05-16",
    age: 10,
    guardianName: "Mr. Chukwu Nwachukwu",
    contactInfo: {
      phone: "+234 924 345 6789",
      email: "chukwu.nwachukwu@email.com",
      address: "33 Independence Layout, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2016-09-01",
    academicRecord: [
      { subject: "English", test: 8, midTerm: 16, exam: 61, total: 85, grade: "A" },
      { subject: "Mathematics", test: 7, midTerm: 15, exam: 57, total: 79, grade: "B" },
      { subject: "Basic Science", test: 8, midTerm: 17, exam: 63, total: 88, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Dust"],
      emergencyContact: "+234 924 345 6790",
    },
  },

  // Primary 3 Students (8 students)
  {
    id: "65",
    fullName: "Chioma Okafor",
    studentId: "PRI017",
    className: "Primary 3",
    gender: "Female",
    dateOfBirth: "2013-11-18",
    age: 11,
    guardianName: "Mr. Peter Okafor",
    contactInfo: {
      phone: "+234 926 456 7890",
      email: "peter.okafor@email.com",
      address: "8 New Haven, Enugu",
    },
    enrollmentStatus: "Transferred",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2015-09-01",
    medicalInfo: {
      allergies: ["Shellfish"],
      emergencyContact: "+234 926 456 7891",
    },
  },
  {
    id: "66",
    fullName: "Adebayo Oni",
    studentId: "PRI018",
    className: "Primary 3",
    gender: "Male",
    dateOfBirth: "2013-09-10",
    age: 11,
    guardianName: "Mrs. Oni Adebayo",
    contactInfo: {
      phone: "+234 928 567 8901",
      email: "oni.adebayo@email.com",
      address: "26 Yaba, Lagos",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2015-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 8, midTerm: 17, exam: 64, total: 89, grade: "A" },
      { subject: "English", test: 9, midTerm: 18, exam: 67, total: 94, grade: "A" },
      { subject: "Basic Science", test: 8, midTerm: 16, exam: 62, total: 86, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 928 567 8902",
    },
  },
  {
    id: "67",
    fullName: "Zainab Usman",
    studentId: "PRI019",
    className: "Primary 3",
    gender: "Female",
    dateOfBirth: "2013-12-02",
    age: 11,
    guardianName: "Alhaji Usman Zainab",
    contactInfo: {
      phone: "+234 930 678 9012",
      email: "usman.zainab@email.com",
      address: "21 Wuse II, Abuja",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2015-09-01",
    academicRecord: [
      { subject: "English", test: 9, midTerm: 18, exam: 68, total: 95, grade: "A" },
      { subject: "Mathematics", test: 8, midTerm: 17, exam: 65, total: 90, grade: "A" },
      { subject: "Civic Education", test: 8, midTerm: 16, exam: 63, total: 87, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 930 678 9013",
    },
  },
  {
    id: "68",
    fullName: "Kelechi Nnaji",
    studentId: "PRI020",
    className: "Primary 3",
    gender: "Male",
    dateOfBirth: "2013-10-14",
    age: 11,
    guardianName: "Mrs. Nnaji Kelechi",
    contactInfo: {
      phone: "+234 932 789 0123",
      email: "nnaji.kelechi@email.com",
      address: "6 Trans Ekulu, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2015-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 7, midTerm: 16, exam: 58, total: 81, grade: "A" },
      { subject: "English", test: 8, midTerm: 17, exam: 62, total: 87, grade: "A" },
      { subject: "Basic Science", test: 7, midTerm: 15, exam: 56, total: 78, grade: "B" },
    ],
    medicalInfo: {
      allergies: ["Fish"],
      emergencyContact: "+234 932 789 0124",
    },
  },
  {
    id: "69",
    fullName: "Adunni Bakare",
    studentId: "PRI021",
    className: "Primary 3",
    gender: "Female",
    dateOfBirth: "2013-08-26",
    age: 11,
    guardianName: "Mr. Bakare Adunni",
    contactInfo: {
      phone: "+234 934 890 1234",
      email: "bakare.adunni@email.com",
      address: "13 Surulere, Lagos",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2015-09-01",
    academicRecord: [
      { subject: "English", test: 9, midTerm: 18, exam: 69, total: 96, grade: "A" },
      { subject: "Mathematics", test: 8, midTerm: 17, exam: 66, total: 91, grade: "A" },
      { subject: "Basic Science", test: 8, midTerm: 16, exam: 63, total: 87, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 934 890 1235",
    },
  },
  {
    id: "70",
    fullName: "Musa Abdullahi",
    studentId: "PRI022",
    className: "Primary 3",
    gender: "Male",
    dateOfBirth: "2013-07-08",
    age: 11,
    guardianName: "Mallam Musa Abdullahi",
    contactInfo: {
      phone: "+234 936 901 2345",
      email: "musa.abdullahi@email.com",
      address: "23 Fagge, Kano",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2015-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 7, midTerm: 15, exam: 54, total: 76, grade: "B" },
      { subject: "English", test: 8, midTerm: 16, exam: 58, total: 82, grade: "A" },
      { subject: "Basic Science", test: 7, midTerm: 16, exam: 57, total: 80, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Citrus"],
      emergencyContact: "+234 936 901 2346",
    },
  },
  {
    id: "71",
    fullName: "Chiamaka Ugwu",
    studentId: "PRI023",
    className: "Primary 3",
    gender: "Female",
    dateOfBirth: "2013-06-20",
    age: 11,
    guardianName: "Dr. Ugwu Chiamaka",
    contactInfo: {
      phone: "+234 938 012 3456",
      email: "ugwu.chiamaka@email.com",
      address: "8 University Road, Nsukka",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2015-09-01",
    academicRecord: [
      { subject: "English", test: 9, midTerm: 17, exam: 67, total: 93, grade: "A" },
      { subject: "Mathematics", test: 8, midTerm: 16, exam: 64, total: 88, grade: "A" },
      { subject: "Civic Education", test: 8, midTerm: 17, exam: 65, total: 90, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 938 012 3457",
    },
  },
  {
    id: "72",
    fullName: "Olumide Ajayi",
    studentId: "PRI024",
    className: "Primary 3",
    gender: "Male",
    dateOfBirth: "2013-05-12",
    age: 11,
    guardianName: "Mr. Ajayi Olumide",
    contactInfo: {
      phone: "+234 940 123 4567",
      email: "ajayi.olumide@email.com",
      address: "17 Oke Ado, Ibadan",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Basic Science", "Civic Education"],
    enrollmentDate: "2015-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 8, midTerm: 16, exam: 61, total: 85, grade: "A" },
      { subject: "English", test: 7, midTerm: 15, exam: 58, total: 80, grade: "A" },
      { subject: "Basic Science", test: 8, midTerm: 17, exam: 63, total: 88, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Strawberries"],
      emergencyContact: "+234 940 123 4568",
    },
  },

  // JSS 1 Students (8 students)
  {
    id: "73",
    fullName: "Kemi Adebayo",
    studentId: "JSS001",
    className: "JSS 1",
    gender: "Female",
    dateOfBirth: "2012-11-25",
    age: 12,
    guardianName: "Mrs. Folake Adebayo",
    contactInfo: {
      phone: "+234 942 234 5678",
      email: "folake.adebayo@email.com",
      address: "25 Ikeja GRA, Lagos",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2024-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 8, midTerm: 16, exam: 58, total: 82, grade: "A" },
      { subject: "English", test: 9, midTerm: 17, exam: 63, total: 89, grade: "A" },
      { subject: "Biology", test: 8, midTerm: 15, exam: 60, total: 83, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 942 234 5679",
    },
  },
  {
    id: "74",
    fullName: "Chukwuemeka Okafor",
    studentId: "JSS002",
    className: "JSS 1",
    gender: "Male",
    dateOfBirth: "2012-09-17",
    age: 12,
    guardianName: "Mr. Peter Okafor",
    contactInfo: {
      phone: "+234 944 345 6789",
      email: "peter.okafor@email.com",
      address: "8 New Haven, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2024-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 7, midTerm: 15, exam: 56, total: 78, grade: "B" },
      { subject: "English", test: 8, midTerm: 16, exam: 61, total: 85, grade: "A" },
      { subject: "Government", test: 8, midTerm: 17, exam: 62, total: 87, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Milk"],
      emergencyContact: "+234 944 345 6790",
    },
  },
  {
    id: "75",
    fullName: "Aisha Bello",
    studentId: "JSS003",
    className: "JSS 1",
    gender: "Female",
    dateOfBirth: "2012-12-09",
    age: 12,
    guardianName: "Alhaji Musa Bello",
    contactInfo: {
      phone: "+234 946 456 7890",
      email: "musa.bello@email.com",
      address: "45 Ahmadu Bello Way, Kaduna",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2024-09-01",
    academicRecord: [
      { subject: "English", test: 9, midTerm: 18, exam: 67, total: 94, grade: "A" },
      { subject: "Mathematics", test: 8, midTerm: 17, exam: 64, total: 89, grade: "A" },
      { subject: "Literature", test: 9, midTerm: 18, exam: 68, total: 95, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 946 456 7891",
    },
  },
  {
    id: "76",
    fullName: "David Okoro",
    studentId: "JSS004",
    className: "JSS 1",
    gender: "Male",
    dateOfBirth: "2012-10-21",
    age: 12,
    guardianName: "Dr. Grace Okoro",
    contactInfo: {
      phone: "+234 948 567 8901",
      email: "grace.okoro@email.com",
      address: "15 Aba Road, Port Harcourt",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2024-09-01",
    academicRecord: [
      { subject: "Biology", test: 8, midTerm: 16, exam: 62, total: 86, grade: "A" },
      { subject: "Mathematics", test: 7, midTerm: 15, exam: 57, total: 79, grade: "B" },
      { subject: "English", test: 8, midTerm: 17, exam: 63, total: 88, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Peanuts"],
      emergencyContact: "+234 948 567 8902",
    },
  },
  {
    id: "77",
    fullName: "Fatima Yusuf",
    studentId: "JSS005",
    className: "JSS 1",
    gender: "Female",
    dateOfBirth: "2012-08-13",
    age: 12,
    guardianName: "Mrs. Amina Yusuf",
    contactInfo: {
      phone: "+234 950 678 9012",
      email: "amina.yusuf@email.com",
      address: "22 Garki, Abuja",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2024-09-01",
    academicRecord: [
      { subject: "Literature", test: 9, midTerm: 18, exam: 69, total: 96, grade: "A" },
      { subject: "English", test: 8, midTerm: 17, exam: 66, total: 91, grade: "A" },
      { subject: "Government", test: 8, midTerm: 16, exam: 63, total: 87, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 950 678 9013",
    },
  },
  {
    id: "78",
    fullName: "Samuel Nwachukwu",
    studentId: "JSS006",
    className: "JSS 1",
    gender: "Male",
    dateOfBirth: "2012-07-05",
    age: 12,
    guardianName: "Mr. Chukwu Nwachukwu",
    contactInfo: {
      phone: "+234 952 789 0123",
      email: "chukwu.nwachukwu@email.com",
      address: "33 Independence Layout, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2024-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 8, midTerm: 16, exam: 60, total: 84, grade: "A" },
      { subject: "Biology", test: 7, midTerm: 15, exam: 58, total: 80, grade: "A" },
      { subject: "English", test: 8, midTerm: 17, exam: 62, total: 87, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Dust"],
      emergencyContact: "+234 952 789 0124",
    },
  },
  {
    id: "79",
    fullName: "Blessing Adamu",
    studentId: "JSS007",
    className: "JSS 1",
    gender: "Female",
    dateOfBirth: "2012-06-17",
    age: 12,
    guardianName: "Mrs. Mary Adamu",
    contactInfo: {
      phone: "+234 954 890 1234",
      email: "mary.adamu@email.com",
      address: "7 Maitama, Abuja",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2024-09-01",
    academicRecord: [
      { subject: "English", test: 9, midTerm: 17, exam: 65, total: 91, grade: "A" },
      { subject: "Literature", test: 8, midTerm: 18, exam: 67, total: 93, grade: "A" },
      { subject: "Mathematics", test: 7, midTerm: 16, exam: 59, total: 82, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 954 890 1235",
    },
  },
  {
    id: "80",
    fullName: "Joseph Eze",
    studentId: "JSS008",
    className: "JSS 1",
    gender: "Male",
    dateOfBirth: "2012-05-29",
    age: 12,
    guardianName: "Mr. Emmanuel Eze",
    contactInfo: {
      phone: "+234 956 901 2345",
      email: "emmanuel.eze@email.com",
      address: "19 Coal City, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2024-09-01",
    academicRecord: [
      { subject: "Government", test: 8, midTerm: 16, exam: 61, total: 85, grade: "A" },
      { subject: "Mathematics", test: 7, midTerm: 15, exam: 56, total: 78, grade: "B" },
      { subject: "Biology", test: 8, midTerm: 17, exam: 63, total: 88, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Shellfish"],
      emergencyContact: "+234 956 901 2346",
    },
  },

  // JSS 2 Students (8 students)
  {
    id: "81",
    fullName: "Emeka Okoro",
    studentId: "JSS009",
    className: "JSS 2",
    gender: "Male",
    dateOfBirth: "2011-11-15",
    age: 13,
    guardianName: "Mr. Chukwu Okoro",
    contactInfo: {
      phone: "+234 958 012 3456",
      email: "chukwu.okoro@email.com",
      address: "15 Aba Road, Port Harcourt",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2023-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 8, midTerm: 15, exam: 55, total: 78, grade: "B" },
      { subject: "English", test: 9, midTerm: 16, exam: 60, total: 85, grade: "A" },
      { subject: "Biology", test: 8, midTerm: 17, exam: 62, total: 87, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Peanuts"],
      emergencyContact: "+234 958 012 3457",
    },
  },
  {
    id: "82",
    fullName: "Adaeze Okonkwo",
    studentId: "JSS010",
    className: "JSS 2",
    gender: "Female",
    dateOfBirth: "2011-09-07",
    age: 13,
    guardianName: "Mrs. Ngozi Okonkwo",
    contactInfo: {
      phone: "+234 960 123 4567",
      email: "ngozi.okonkwo@email.com",
      address: "5 Awka Road, Onitsha",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2023-09-01",
    academicRecord: [
      { subject: "Literature", test: 9, midTerm: 18, exam: 68, total: 95, grade: "A" },
      { subject: "English", test: 8, midTerm: 17, exam: 65, total: 90, grade: "A" },
      { subject: "Government", test: 8, midTerm: 16, exam: 63, total: 87, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 960 123 4568",
    },
  },
  {
    id: "83",
    fullName: "Kayode Adeyemi",
    studentId: "JSS011",
    className: "JSS 2",
    gender: "Male",
    dateOfBirth: "2011-12-19",
    age: 13,
    guardianName: "Prof. Adeyemi Kayode",
    contactInfo: {
      phone: "+234 962 234 5678",
      email: "adeyemi.kayode@email.com",
      address: "18 Bodija, Ibadan",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2023-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 8, midTerm: 17, exam: 64, total: 89, grade: "A" },
      { subject: "Biology", test: 7, midTerm: 16, exam: 59, total: 82, grade: "A" },
      { subject: "English", test: 8, midTerm: 15, exam: 57, total: 80, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Nuts"],
      emergencyContact: "+234 962 234 5679",
    },
  },
  {
    id: "84",
    fullName: "Hauwa Garba",
    studentId: "JSS012",
    className: "JSS 2",
    gender: "Female",
    dateOfBirth: "2011-10-11",
    age: 13,
    guardianName: "Dr. Garba Hauwa",
    contactInfo: {
      phone: "+234 964 345 6789",
      email: "garba.hauwa@email.com",
      address: "9 Ungwan Rimi, Kaduna",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2023-09-01",
    academicRecord: [
      { subject: "English", test: 9, midTerm: 18, exam: 67, total: 94, grade: "A" },
      { subject: "Literature", test: 8, midTerm: 17, exam: 66, total: 91, grade: "A" },
      { subject: "Mathematics", test: 8, midTerm: 16, exam: 62, total: 86, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 964 345 6790",
    },
  },
  {
    id: "85",
    fullName: "Daniel Okpara",
    studentId: "JSS013",
    className: "JSS 2",
    gender: "Male",
    dateOfBirth: "2011-08-23",
    age: 13,
    guardianName: "Mr. Okpara Daniel",
    contactInfo: {
      phone: "+234 966 456 7890",
      email: "okpara.daniel@email.com",
      address: "14 Owerri Road, Aba",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2023-09-01",
    academicRecord: [
      { subject: "Government", test: 8, midTerm: 16, exam: 60, total: 84, grade: "A" },
      { subject: "Mathematics", test: 7, midTerm: 15, exam: 56, total: 78, grade: "B" },
      { subject: "Biology", test: 8, midTerm: 17, exam: 62, total: 87, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Soy"],
      emergencyContact: "+234 966 456 7891",
    },
  },
  {
    id: "86",
    fullName: "Zainab Usman",
    studentId: "JSS014",
    className: "JSS 2",
    gender: "Female",
    dateOfBirth: "2011-07-15",
    age: 13,
    guardianName: "Alhaji Usman Zainab",
    contactInfo: {
      phone: "+234 968 567 8901",
      email: "usman.zainab@email.com",
      address: "21 Wuse II, Abuja",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2023-09-01",
    academicRecord: [
      { subject: "Literature", test: 9, midTerm: 17, exam: 66, total: 92, grade: "A" },
      { subject: "English", test: 8, midTerm: 18, exam: 64, total: 90, grade: "A" },
      { subject: "Government", test: 8, midTerm: 16, exam: 61, total: 85, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 968 567 8902",
    },
  },
  {
    id: "87",
    fullName: "Victor Nnaji",
    studentId: "JSS015",
    className: "JSS 2",
    gender: "Male",
    dateOfBirth: "2011-06-07",
    age: 13,
    guardianName: "Mrs. Nnaji Victor",
    contactInfo: {
      phone: "+234 970 678 9012",
      email: "nnaji.victor@email.com",
      address: "6 Trans Ekulu, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2023-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 8, midTerm: 15, exam: 57, total: 80, grade: "A" },
      { subject: "Biology", test: 7, midTerm: 16, exam: 59, total: 82, grade: "A" },
      { subject: "English", test: 8, midTerm: 17, exam: 63, total: 88, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Fish"],
      emergencyContact: "+234 970 678 9013",
    },
  },
  {
    id: "88",
    fullName: "Ifeoma Okwu",
    studentId: "JSS016",
    className: "JSS 2",
    gender: "Female",
    dateOfBirth: "2011-05-19",
    age: 13,
    guardianName: "Mrs. Okwu Ifeoma",
    contactInfo: {
      phone: "+234 972 789 0123",
      email: "okwu.ifeoma@email.com",
      address: "20 Ogui Road, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2023-09-01",
    academicRecord: [
      { subject: "English", test: 9, midTerm: 18, exam: 68, total: 95, grade: "A" },
      { subject: "Literature", test: 8, midTerm: 17, exam: 65, total: 90, grade: "A" },
      { subject: "Government", test: 8, midTerm: 16, exam: 62, total: 86, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 972 789 0124",
    },
  },

  // JSS 3 Students (8 students)
  {
    id: "89",
    fullName: "Chinedu Obi",
    studentId: "JSS017",
    className: "JSS 3",
    gender: "Male",
    dateOfBirth: "2010-11-06",
    age: 14,
    guardianName: "Dr. Obi Chinedu",
    contactInfo: {
      phone: "+234 974 890 1234",
      email: "obi.chinedu@email.com",
      address: "27 Asaba Road, Onitsha",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2022-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 8, midTerm: 16, exam: 60, total: 84, grade: "A" },
      { subject: "English", test: 9, midTerm: 17, exam: 63, total: 89, grade: "A" },
      { subject: "Biology", test: 8, midTerm: 15, exam: 60, total: 83, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Wheat"],
      emergencyContact: "+234 974 890 1235",
    },
  },
  {
    id: "90",
    fullName: "Maryam Aliyu",
    studentId: "JSS018",
    className: "JSS 3",
    gender: "Female",
    dateOfBirth: "2010-09-29",
    age: 14,
    guardianName: "Mrs. Aliyu Maryam",
    contactInfo: {
      phone: "+234 976 901 2345",
      email: "aliyu.maryam@email.com",
      address: "4 Barnawa, Kaduna",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2022-09-01",
    academicRecord: [
      { subject: "Literature", test: 9, midTerm: 18, exam: 67, total: 94, grade: "A" },
      { subject: "English", test: 8, midTerm: 17, exam: 65, total: 90, grade: "A" },
      { subject: "Government", test: 8, midTerm: 16, exam: 63, total: 87, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 976 901 2346",
    },
  },
  {
    id: "91",
    fullName: "Tochukwu Eze",
    studentId: "JSS019",
    className: "JSS 3",
    gender: "Male",
    dateOfBirth: "2010-12-11",
    age: 14,
    guardianName: "Mr. Eze Tochukwu",
    contactInfo: {
      phone: "+234 978 012 3456",
      email: "eze.tochukwu@email.com",
      address: "16 Nike Lake, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2022-09-01",
    academicRecord: [
      { subject: "Biology", test: 8, midTerm: 16, exam: 62, total: 86, grade: "A" },
      { subject: "Mathematics", test: 7, midTerm: 15, exam: 57, total: 79, grade: "B" },
      { subject: "English", test: 8, midTerm: 17, exam: 63, total: 88, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Dairy"],
      emergencyContact: "+234 978 012 3457",
    },
  },
  {
    id: "92",
    fullName: "Funmi Adebola",
    studentId: "JSS020",
    className: "JSS 3",
    gender: "Female",
    dateOfBirth: "2010-10-23",
    age: 14,
    guardianName: "Mrs. Adebola Funmi",
    contactInfo: {
      phone: "+234 980 123 4567",
      email: "adebola.funmi@email.com",
      address: "10 Abeokuta Road, Lagos",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2022-09-01",
    academicRecord: [
      { subject: "Literature", test: 9, midTerm: 17, exam: 65, total: 91, grade: "A" },
      { subject: "English", test: 8, midTerm: 18, exam: 64, total: 90, grade: "A" },
      { subject: "Mathematics", test: 7, midTerm: 16, exam: 59, total: 82, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 980 123 4568",
    },
  },
  {
    id: "93",
    fullName: "Abdullahi Musa",
    studentId: "JSS021",
    className: "JSS 3",
    gender: "Male",
    dateOfBirth: "2010-08-15",
    age: 14,
    guardianName: "Mallam Musa Abdullahi",
    contactInfo: {
      phone: "+234 982 234 5678",
      email: "musa.abdullahi@email.com",
      address: "23 Fagge, Kano",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2022-09-01",
    academicRecord: [
      { subject: "Government", test: 8, midTerm: 16, exam: 61, total: 85, grade: "A" },
      { subject: "Mathematics", test: 7, midTerm: 15, exam: 56, total: 78, grade: "B" },
      { subject: "Biology", test: 8, midTerm: 17, exam: 63, total: 88, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Citrus"],
      emergencyContact: "+234 982 234 5679",
    },
  },
  {
    id: "94",
    fullName: "Chioma Ugwu",
    studentId: "JSS022",
    className: "JSS 3",
    gender: "Female",
    dateOfBirth: "2010-07-07",
    age: 14,
    guardianName: "Dr. Ugwu Chioma",
    contactInfo: {
      phone: "+234 984 345 6789",
      email: "ugwu.chioma@email.com",
      address: "8 University Road, Nsukka",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2022-09-01",
    academicRecord: [
      { subject: "Literature", test: 9, midTerm: 17, exam: 66, total: 92, grade: "A" },
      { subject: "English", test: 8, midTerm: 18, exam: 64, total: 90, grade: "A" },
      { subject: "Government", test: 8, midTerm: 16, exam: 61, total: 85, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 984 345 6790",
    },
  },
  {
    id: "95",
    fullName: "Olumide Ajayi",
    studentId: "JSS023",
    className: "JSS 3",
    gender: "Male",
    dateOfBirth: "2010-06-19",
    age: 14,
    guardianName: "Mr. Ajayi Olumide",
    contactInfo: {
      phone: "+234 986 456 7890",
      email: "ajayi.olumide@email.com",
      address: "17 Oke Ado, Ibadan",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2022-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 8, midTerm: 16, exam: 61, total: 85, grade: "A" },
      { subject: "Biology", test: 7, midTerm: 15, exam: 56, total: 78, grade: "B" },
      { subject: "English", test: 8, midTerm: 17, exam: 63, total: 88, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Strawberries"],
      emergencyContact: "+234 986 456 7891",
    },
  },
  {
    id: "96",
    fullName: "Kemi Adebayo",
    studentId: "JSS024",
    className: "JSS 3",
    gender: "Female",
    dateOfBirth: "2010-05-11",
    age: 14,
    guardianName: "Mrs. Folake Adebayo",
    contactInfo: {
      phone: "+234 988 567 8901",
      email: "folake.adebayo@email.com",
      address: "25 Ikeja GRA, Lagos",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2022-09-01",
    academicRecord: [
      { subject: "English", test: 9, midTerm: 17, exam: 65, total: 91, grade: "A" },
      { subject: "Literature", test: 8, midTerm: 18, exam: 67, total: 93, grade: "A" },
      { subject: "Mathematics", test: 7, midTerm: 16, exam: 59, total: 82, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 988 567 8902",
    },
  },

  // SS 1 Students (4 students)
  {
    id: "97",
    fullName: "Amaka Okeke",
    studentId: "SSS001",
    className: "SS 1",
    gender: "Female",
    dateOfBirth: "2009-11-02",
    age: 15,
    guardianName: "Mrs. Okeke Amaka",
    contactInfo: {
      phone: "+234 990 678 9012",
      email: "okeke.amaka@email.com",
      address: "27 Port Harcourt City, Rivers",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2021-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 8, midTerm: 16, exam: 60, total: 84, grade: "A" },
      { subject: "English", test: 9, midTerm: 17, exam: 63, total: 89, grade: "A" },
      { subject: "Biology", test: 8, midTerm: 15, exam: 60, total: 83, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 990 678 9013",
    },
  },
  {
    id: "98",
    fullName: "Kabiru Musa",
    studentId: "SSS002",
    className: "SS 1",
    gender: "Male",
    dateOfBirth: "2009-09-24",
    age: 15,
    guardianName: "Alhaji Musa Kabiru",
    contactInfo: {
      phone: "+234 992 789 0123",
      email: "musa.kabiru@email.com",
      address: "22 Kano Municipal, Kano",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2021-09-01",
    academicRecord: [
      { subject: "Government", test: 8, midTerm: 16, exam: 61, total: 85, grade: "A" },
      { subject: "Mathematics", test: 7, midTerm: 15, exam: 56, total: 78, grade: "B" },
      { subject: "Biology", test: 8, midTerm: 17, exam: 63, total: 88, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Dust"],
      emergencyContact: "+234 992 789 0124",
    },
  },
  {
    id: "99",
    fullName: "Ngozi Okorocha",
    studentId: "SSS003",
    className: "SS 1",
    gender: "Female",
    dateOfBirth: "2009-12-05",
    age: 15,
    guardianName: "Mrs. Okorocha Ngozi",
    contactInfo: {
      phone: "+234 994 890 1234",
      email: "okorocha.ngozi@email.com",
      address: "14 Onitsha South, Anambra",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2021-09-01",
    academicRecord: [
      { subject: "Literature", test: 9, midTerm: 18, exam: 67, total: 94, grade: "A" },
      { subject: "English", test: 8, midTerm: 17, exam: 65, total: 90, grade: "A" },
      { subject: "Mathematics", test: 8, midTerm: 16, exam: 62, total: 86, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 994 890 1235",
    },
  },
  {
    id: "100",
    fullName: "Bode Adebayo",
    studentId: "SSS004",
    className: "SS 1",
    gender: "Male",
    dateOfBirth: "2009-10-17",
    age: 15,
    guardianName: "Mr. Adebayo Bode",
    contactInfo: {
      phone: "+234 996 901 2345",
      email: "adebayo.bode@email.com",
      address: "17 Ibadan South West, Oyo",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2021-09-01",
    academicRecord: [
      { subject: "Biology", test: 8, midTerm: 16, exam: 61, total: 85, grade: "A" },
      { subject: "Mathematics", test: 7, midTerm: 15, exam: 58, total: 80, grade: "A" },
      { subject: "English", test: 8, midTerm: 17, exam: 63, total: 88, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Pollen"],
      emergencyContact: "+234 996 901 2346",
    },
  },

  // SS 2 Students (4 students)
  {
    id: "101",
    fullName: "Ifeoma Eze",
    studentId: "SSS005",
    className: "SS 2",
    gender: "Female",
    dateOfBirth: "2008-11-18",
    age: 16,
    guardianName: "Mrs. Eze Ifeoma",
    contactInfo: {
      phone: "+234 998 012 3456",
      email: "eze.ifeoma@email.com",
      address: "28 Owerri West, Imo",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2020-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 8, midTerm: 16, exam: 60, total: 84, grade: "A" },
      { subject: "English", test: 9, midTerm: 17, exam: 63, total: 89, grade: "A" },
      { subject: "Biology", test: 8, midTerm: 15, exam: 60, total: 83, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 998 012 3457",
    },
  },
  {
    id: "102",
    fullName: "Umar Sadiq",
    studentId: "SSS006",
    className: "SS 2",
    gender: "Male",
    dateOfBirth: "2008-09-10",
    age: 16,
    guardianName: "Alhaji Sadiq Umar",
    contactInfo: {
      phone: "+234 999 123 4567",
      email: "sadiq.umar@email.com",
      address: "23 Zaria City, Kaduna",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2020-09-01",
    academicRecord: [
      { subject: "Government", test: 8, midTerm: 16, exam: 61, total: 85, grade: "A" },
      { subject: "Mathematics", test: 7, midTerm: 15, exam: 56, total: 78, grade: "B" },
      { subject: "Biology", test: 8, midTerm: 17, exam: 63, total: 88, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Nuts"],
      emergencyContact: "+234 999 123 4568",
    },
  },
  {
    id: "103",
    fullName: "Onyinye Okafor",
    studentId: "SSS007",
    className: "SS 2",
    gender: "Female",
    dateOfBirth: "2008-12-02",
    age: 16,
    guardianName: "Mrs. Okafor Onyinye",
    contactInfo: {
      phone: "+234 997 234 5678",
      email: "okafor.onyinye@email.com",
      address: "16 Nsukka Town, Enugu",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2020-09-01",
    academicRecord: [
      { subject: "Literature", test: 9, midTerm: 18, exam: 67, total: 94, grade: "A" },
      { subject: "English", test: 8, midTerm: 17, exam: 65, total: 90, grade: "A" },
      { subject: "Mathematics", test: 8, midTerm: 16, exam: 62, total: 86, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 997 234 5679",
    },
  },
  {
    id: "104",
    fullName: "Babatunde Adebayo",
    studentId: "SSS008",
    className: "SS 2",
    gender: "Male",
    dateOfBirth: "2008-10-14",
    age: 16,
    guardianName: "Mr. Adebayo Babatunde",
    contactInfo: {
      phone: "+234 995 345 6789",
      email: "adebayo.babatunde@email.com",
      address: "21 Osogbo City, Osun",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2020-09-01",
    academicRecord: [
      { subject: "Biology", test: 8, midTerm: 16, exam: 61, total: 85, grade: "A" },
      { subject: "Mathematics", test: 7, midTerm: 15, exam: 58, total: 80, grade: "A" },
      { subject: "English", test: 8, midTerm: 17, exam: 63, total: 88, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Eggs"],
      emergencyContact: "+234 995 345 6790",
    },
  },

  // SS 3 Students (4 students)
  {
    id: "105",
    fullName: "Hadiza Musa",
    studentId: "SSS009",
    className: "SS 3",
    gender: "Female",
    dateOfBirth: "2007-11-05",
    age: 17,
    guardianName: "Mrs. Musa Hadiza",
    contactInfo: {
      phone: "+234 993 456 7890",
      email: "musa.hadiza@email.com",
      address: "34 Kano Road, Jos",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2019-09-01",
    academicRecord: [
      { subject: "Mathematics", test: 8, midTerm: 16, exam: 60, total: 84, grade: "A" },
      { subject: "English", test: 9, midTerm: 17, exam: 63, total: 89, grade: "A" },
      { subject: "Biology", test: 8, midTerm: 15, exam: 60, total: 83, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 993 456 7891",
    },
  },
  {
    id: "106",
    fullName: "Ikenna Okeke",
    studentId: "SSS010",
    className: "SS 3",
    gender: "Male",
    dateOfBirth: "2007-09-27",
    age: 17,
    guardianName: "Mr. Okeke Ikenna",
    contactInfo: {
      phone: "+234 991 567 8901",
      email: "okeke.ikenna@email.com",
      address: "21 Aba Road, Umuahia",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2019-09-01",
    academicRecord: [
      { subject: "Government", test: 8, midTerm: 16, exam: 61, total: 85, grade: "A" },
      { subject: "Mathematics", test: 7, midTerm: 15, exam: 56, total: 78, grade: "B" },
      { subject: "Biology", test: 8, midTerm: 17, exam: 63, total: 88, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Fish"],
      emergencyContact: "+234 991 567 8902",
    },
  },
  {
    id: "107",
    fullName: "Zainab Usman",
    studentId: "SSS011",
    className: "SS 3",
    gender: "Female",
    dateOfBirth: "2007-12-19",
    age: 17,
    guardianName: "Mrs. Usman Zainab",
    contactInfo: {
      phone: "+234 999 678 9012",
      email: "usman.zainab@email.com",
      address: "26 Sokoto Road, Kaduna",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2019-09-01",
    academicRecord: [
      { subject: "Literature", test: 9, midTerm: 18, exam: 67, total: 94, grade: "A" },
      { subject: "English", test: 8, midTerm: 17, exam: 65, total: 90, grade: "A" },
      { subject: "Mathematics", test: 8, midTerm: 16, exam: 62, total: 86, grade: "A" },
    ],
    medicalInfo: {
      allergies: [],
      emergencyContact: "+234 999 678 9013",
    },
  },
  {
    id: "108",
    fullName: "Olumide Adebayo",
    studentId: "SSS012",
    className: "SS 3",
    gender: "Male",
    dateOfBirth: "2007-10-11",
    age: 17,
    guardianName: "Mr. Adebayo Olumide",
    contactInfo: {
      phone: "+234 997 789 0123",
      email: "adebayo.olumide@email.com",
      address: "23 Ibadan North, Oyo",
    },
    enrollmentStatus: "Active",
    subjects: ["Mathematics", "English", "Biology", "Government", "Literature"],
    enrollmentDate: "2019-09-01",
    academicRecord: [
      { subject: "Biology", test: 8, midTerm: 16, exam: 61, total: 85, grade: "A" },
      { subject: "Mathematics", test: 7, midTerm: 15, exam: 58, total: 80, grade: "A" },
      { subject: "English", test: 8, midTerm: 17, exam: 63, total: 88, grade: "A" },
    ],
    medicalInfo: {
      allergies: ["Strawberries"],
      emergencyContact: "+234 997 789 0124",
    },
  },
]

// Helper function to get class summary
export const getClassSummary = (students: Student[]) => {
  const summary: Record<string, number> = {}
  students.forEach((student) => {
    if (student.enrollmentStatus === "Active") {
      summary[student.className] = (summary[student.className] || 0) + 1
    }
  })
  return summary
}

// Helper function to get enrollment status summary
export const getEnrollmentSummary = (students: Student[]) => {
  const summary: Record<string, number> = {}
  students.forEach((student) => {
    summary[student.enrollmentStatus] = (summary[student.enrollmentStatus] || 0) + 1
  })
  return summary
}

// Enhanced helper functions
export const getStudentsByClass = (className: string): Student[] => {
  return sampleStudents.filter((student) => student.className === className)
}

export const getStudentsByLevel = (level: string): Student[] => {
  const levelClasses = classGroups.find((group) => group.level === level)?.classes || []
  return sampleStudents.filter((student) => levelClasses.includes(student.className))
}

export const getStudentsByGender = (gender: "Male" | "Female"): Student[] => {
  return sampleStudents.filter((student) => student.gender === gender)
}

export const getStudentsByStatus = (status: string): Student[] => {
  return sampleStudents.filter((student) => student.enrollmentStatus === status)
}

export const getAgeDistribution = (): Record<number, number> => {
  const distribution: Record<number, number> = {}
  sampleStudents.forEach((student) => {
    distribution[student.age] = (distribution[student.age] || 0) + 1
  })
  return distribution
}

export const getGenderDistribution = (): Record<string, number> => {
  const distribution: Record<string, number> = { Male: 0, Female: 0 }
  sampleStudents.forEach((student) => {
    distribution[student.gender]++
  })
  return distribution
}

export const getLevelDistribution = (): Record<string, number> => {
  const distribution: Record<string, number> = {}
  classGroups.forEach((group) => {
    const levelStudents = getStudentsByLevel(group.level)
    distribution[group.level] = levelStudents.length
  })
  return distribution
}

// Search functionality
export const searchStudents = (query: string): Student[] => {
  const lowercaseQuery = query.toLowerCase()
  return sampleStudents.filter(
    (student) =>
      student.fullName.toLowerCase().includes(lowercaseQuery) ||
      student.studentId.toLowerCase().includes(lowercaseQuery) ||
      student.guardianName.toLowerCase().includes(lowercaseQuery) ||
      student.className.toLowerCase().includes(lowercaseQuery),
  )
}

// Academic performance helpers
export const getTopPerformers = (limit = 10): Student[] => {
  return sampleStudents
    .filter((student) => student.academicRecord && student.academicRecord.length > 0)
    .sort((a, b) => {
      const avgA = a.academicRecord!.reduce((sum, record) => sum + record.total, 0) / a.academicRecord!.length
      const avgB = b.academicRecord!.reduce((sum, record) => sum + record.total, 0) / b.academicRecord!.length
      return avgB - avgA
    })
    .slice(0, limit)
}

export const getClassAverage = (className: string): number => {
  const classStudents = getStudentsByClass(className)
  const studentsWithRecords = classStudents.filter(
    (student) => student.academicRecord && student.academicRecord.length > 0,
  )

  if (studentsWithRecords.length === 0) return 0

  const totalAverage = studentsWithRecords.reduce((sum, student) => {
    const studentAvg =
      student.academicRecord!.reduce((recordSum, record) => recordSum + record.total, 0) /
      student.academicRecord!.length
    return sum + studentAvg
  }, 0)

  return Math.round(totalAverage / studentsWithRecords.length)
}
